[package]
name = "firkin_units"
version = "0.2.0"
edition = "2024"
description = "Unit-attached numbers for scientific or engineering calculations"
readme = "README.md"
license-file = "LICENSE.md"
repository = "https://github.com/janKaje/firkin"
homepage = "https://github.com/janKaje/firkin"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "firkin"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.29.2", features = ["abi3-py38"]}

[build-dependencies]
csv = "1.4.0"
toml = "1.1.4"
serde = "1.0.229"
