from typing import Optional, Self

class Firkin:

    @classmethod
    def unit(cls, query:str) -> Self: ...

    @classmethod
    def constant(cls, query:str) -> Self: ...

    @classmethod
    def empty(cls) -> Self: ...

    @classmethod
    def custom(cls, name:str, abbr:str, definition:Self|LogFirkin|float|int|str) -> Self: ...

    def as_unit(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def as_number(self, other:Self|LogFirkin|float|int|str|None=None, scale:bool=False) -> float: ...

    def as_unitless(self) -> float: ...

    def as_base_units(self) -> Self: ...

    def descriptive(self) -> str: ...

    def latex(self) -> str: ...

    def round_sfig(self, n_sig_figs:int) -> Self: ...

    def simplify(self) -> Self: ...

    def simplify_inplace(self) -> None: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __mul__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __rmul__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __div__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __truediv__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __rdiv__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __rtruediv__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __add__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __radd__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __sub__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __rsub__(self, other:Self|LogFirkin|float|int|str) -> Self: ...

    def __pow__(self, other:Self|LogFirkin|float|int|str, modulus:float|int|None=None) -> Self: ...

    def __rpow__(self, other:Self|LogFirkin|float|int|str, modulus:float|int|None=None) -> Self: ...

    def __lt__(self, other:Self|LogFirkin|float|int|str) -> bool: ...

    def __le__(self, other:Self|LogFirkin|float|int|str) -> bool: ...

    def __gt__(self, other:Self|LogFirkin|float|int|str) -> bool: ...

    def __ge__(self, other:Self|LogFirkin|float|int|str) -> bool: ...

    def __eq__(self, other:Self|LogFirkin|float|int|str) -> bool: ...

    def __ne__(self, other:Self|LogFirkin|float|int|str) -> bool: ...

    def __abs__(self) -> Self: ...

    def __int__(self) -> int: ...

    def __float__(self) -> float: ...

    def __round__(self, ndigits:int=None) -> Self: ...

    def __exp__(self) -> float: ...

    def __log__(self) -> float: ...

    def __log10__(self) -> float: ...

class LogFirkin:

    @classmethod
    def unit(cls, query:str) -> Self:
        """
        Create a new LogFirkin instance by searching for a unit name or symbol.

        Parameters
        ----------
        query : str
            The query by which to look up the unit. Currently, only the neper
            (Np), bel (B), and decibel (dB) are supported.

        Returns
        -------
        LogFirkin
            The new LogFirkin instance.
        """
        ...

    def as_unit(self, other:Self) -> Self:
        """
        Converts self into the unit of other.
        """

    def as_number(self, other:Optional[Self]=None) -> float:
        """
        Returns the unit value of self, optionally converted to another unit
        using the other parameter. Note that this does not resolve the
        logarithmic ratio like as_unitless does.

        Examples
        --------
        >>> from firkin.units import decibel as dB, bel
        >>> my_ratio = 12*dB
        >>> my_ratio
        12 [dB]
        >>> my_ratio.as_unitless()
        15.848931924611145
        >>> my_ratio.as_number()
        12.0
        >>> my_ratio.as_number(bel)
        1.2000000000000002
        """

    def as_unitless(self) -> float:
        """
        Returns the instance as a unitless number, converting the unit into an
        appropriate logarithmic ratio.

        Examples
        --------
        >>> from firkin.units import decibel as dB
        >>> ratio = 21*dB
        >>> ratio.as_unitless()
        125.89254117941687
        """
        ...

    def round_sfig(self, n_sig_figs:int) -> float:
        """
        Returns the equivalent of `as_unitless`, rounded to the given number of
        significant figures.
        """

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __mul__(self, other:Self|float|int) -> Self|float: ...

    def __rmul__(self, other:Self|float|int) -> Self|float: ...

    def __div__(self, other:Self|float|int) -> Self|float: ...

    def __truediv__(self, other:Self|float|int) -> Self|float: ...

    def __rdiv__(self, other:Self|float|int) -> float: ...

    def __rtruediv__(self, other:Self|float|int) -> float: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __add__(self, other:Self|float|int) -> Self|float: ...

    def __radd__(self, other:Self|float|int) -> Self|float: ...

    def __sub__(self, other:Self|float|int) -> Self|float: ...

    def __rsub__(self, other:Self|float|int) -> Self|float: ...

    def __pow__(self, other:Self|float|int, modulus:float|int|None=None) -> float: ...

    def __rpow__(self, other:Self|float|int, modulus:float|int|None=None) -> float: ...

    def __lt__(self, other:Self|float|int) -> bool: ...

    def __le__(self, other:Self|float|int) -> bool: ...

    def __gt__(self, other:Self|float|int) -> bool: ...

    def __ge__(self, other:Self|float|int) -> bool: ...

    def __eq__(self, other:Self|float|int) -> bool: ...

    def __ne__(self, other:Self|float|int) -> bool: ...

    def __abs__(self) -> float: ...

    def __int__(self) -> int: ...

    def __float__(self) -> float: ...

    def __round__(self, ndigits:int=None) -> float: ...

    def __exp__(self) -> float: ...

    def __log__(self) -> float: ...

    def __log10__(self) -> float: ...