
[second]
abbr = "s"
python_var_name = "second"

[meter]
abbr = "m"
python_var_name = "meter"

[kilogram]
abbr = "kg"
python_var_name = "kilogram"

[ampere]
abbr = "A"
python_var_name = "ampere"

[kelvin]
abbr = "K"
python_var_name = "kelvin"

[mole]
abbr = "mol"
python_var_name = "mole"

[candela]
abbr = "cd"
python_var_name = "candela"

[USD]
abbr = "USD"
python_var_name = "USD"
